### ISSUE TITLE
能否增加博客搬家的功能？

### ISSUE THREAD

**Issue by painezeng** [onblog/BlogHelper#18]
对已有平台进行转发博客到另一个平台。

**Comment by ystcode** [comment]
可

**Comment by yhybulider** [comment]
这个功能还没出来是吗

**Comment by ystcode** [comment]
下周吧。别着急哈哈

**Comment by yhybulider** [comment]
hhh，好的，辛苦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"薛勤"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月22日(星期五) 中午11:01
收件人:&nbsp;"ystcode/BlogHelper"<BlogHelper@noreply.github.com&gt;;
抄送:&nbsp;"Fire"<1065205068@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ystcode/BlogHelper] 能否增加博客搬家的功能？ (#18)





 
下周吧。别着急哈哈

**Comment by painezeng** [comment]
嗯，感谢感谢。

**Comment by onblog** [comment]
例如csdn是支持博客搬家功能的，但像博客园这种对每天文章的发布数量都有限制，着实不好做，可以搞一个各个博客平台文章一键download到本地的功能，有需求吗？
