### ISSUE TITLE
找不到 "一键发布" 的按钮

### ISSUE THREAD

**Issue by zhangxiann** [onblog/BlogHelper#45]
1. 你使用的操作系统是：
Windows
2. 你使用的本软件版本号是：

不知道怎么查看版本。点击`版本查询`，没有反应。
![image](https://user-images.githubusercontent.com/12131262/90465732-8ee9ce80-e142-11ea-99cd-4a364036e0e3.png)

3. 请详细叙述你的问题：
我用了一下，**每个平台都需要单独点击发布**。没有 README 里面说的 `一键发布本地文章到知乎、简书、博客园、CSDN、掘金、SegmentFault(思否)、开源中国等平台` 的功能。
![image](https://user-images.githubusercontent.com/12131262/90465594-44685200-e142-11ea-92e2-30a77b587fce.png)

**请问哪里有"一键发布"的按钮？如何使用这个功能**

**Comment by onblog** [comment]
没有，别用了。

**Comment by zhangxiann** [comment]
好的，那建议修改 README 呢

**Comment by onblog** [comment]
建议无效
