### ISSUE TITLE
使用文档

### ISSUE THREAD

**Issue by lw5946** [onblog/BlogHelper#51]
**您的功能请求是否与问题相关？请描述**
使用文档

**描述您想使用**
软件只存放于系统托盘的确是很轻量、方便，但是如何使用它呢？我在哪里编辑文章之后，再通过它发布呢？是自己写完了md文件之后，再通过博客 -> 平台（如：思否） -> 发布 -> 选择md文件，就可以了吗？

**Comment by onblog** [comment]
大胆尝试下
