### ISSUE TITLE
掘金上传不了数据

### ISSUE THREAD

**Issue by AncientFairy** [onblog/BlogHelper#53]
1. 你使用的操作系统是：Win10 

2. 你使用的本软件版本号是：1.0.25

3. 请详细叙述你的问题：掘金上传不了数据

4. 用于问题复现的数据：
![掘金报错](https://user-images.githubusercontent.com/25677587/92339126-1e055900-f0e7-11ea-832c-13fb82dc33ec.png)

**Comment by onblog** [comment]
掘金API换了

**Comment by wangbs95** [comment]
> 掘金API换了

- 感谢大佬工具，终于有不使用图床的既可以积累自己个人博客又可以发布博客平台的解决方案了！！！
- 敢问大佬掘金 API 啥时候出修复版呀

**Comment by onblog** [comment]
掘金一键发布已在1.0.27版本修复！
