### ISSUE TITLE
README 中的图片无法正常显示

### ISSUE THREAD

**Issue by Higurashi-kagome** [onblog/BlogHelper#62]
[README.md](https://github.com/onblog/BlogHelper/blob/master/src/plugins/README.md) 中的图片无法正常显示。

**Comment by onblog** [comment]
参数文章自行解决：[解决访问Github图片无法加载的问题](https://onblogs.net/2021/01/24/Github%E7%BD%91%E7%AB%99%E7%9A%84%E5%9B%BE%E7%89%87%E4%B8%8D%E6%98%BE%E7%A4%BA%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3/)

**Comment by Higurashi-kagome** [comment]
似乎不是这个的原因。并不是指仓库根目录的 README.md，而是 [BlogHelper/src/plugins/README.md](https://github.com/onblog/BlogHelper/blob/master/src/plugins/README.md)。
