### ISSUE TITLE
能否出一个完整的使用教程呢？新手在使用的过程中会遇到一些莫名其妙的错误

### ISSUE THREAD

**Issue by LvShuaiChao** [onblog/BlogHelper#65]
1. 你使用的操作系统是：Win10

2. 你使用的本软件版本号是：1.0.28

3. 请详细叙述你的问题：打开图床以及一些其他配置的时候，会出现，“该文件没有与之关联的应用来执行，该操作请安装应用，若已经安装应用，请在默认应用设置页面中创建关联”的弹窗，这是怎么一回事

4. 用于问题复现的数据：

**Comment by LvShuaiChao** [comment]
![image](https://user-images.githubusercontent.com/35528109/110308426-0d548200-803b-11eb-9c57-28ebe717e143.png)

**Comment by onblog** [comment]
这个错误意思是你的计算机没有支持.json文件的程序，你可以安装个 vs code、sublime text等。
