### ISSUE TITLE
win10 博客园md文章js报错

### ISSUE THREAD

**Issue by Ink-kai** [onblog/BlogHelper#68]
1. 你使用的操作系统是：win10 x64

2. 你使用的本软件版本号是：1.0.28

3. 请详细叙述你的问题：博客园上传本地md文章报错
![image](https://user-images.githubusercontent.com/44126939/112808054-2cc75380-90ab-11eb-8f4c-516733965792.png)

4. 用于问题复现的数据：

**Comment by slayercjc** [comment]
我也是这个问题，，，，不知道怎么解决

**Comment by onblog** [comment]
1.0.30版本已修复
