### ISSUE TITLE
博客园发表错误

### ISSUE THREAD

**Issue by leon9dragon** [onblog/BlogHelper#69]
1. 你使用的操作系统是：   
MacOS    
2. 你使用的本软件版本号是： 
1.0.28  
3. 请详细叙述你的问题：
发表博客园文章出现js错误   
4. 用于问题复现的数据：   
![image](https://user-images.githubusercontent.com/49860984/114304164-50a38400-9b04-11eb-9c28-126842f559c6.png)

**Comment by guchangan1** [comment]
metoo

**Comment by slayercjc** [comment]
metoo 作者能解决下吗？

**Comment by onblog** [comment]
1.0.30版本已修复
