### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by happysnaker** [onblog/BlogHelper#74]
1. 你使用的操作系统是：win

2. 你使用的本软件版本号是：最新

3. 请详细叙述你的问题：博客园上传报JS错误

4. 用于问题复现的数据：
![image](https://user-images.githubusercontent.com/73147033/129659158-e215b59a-e624-477a-97fc-d314d3fa2899.png)

**Comment by guchangan1** [comment]
确实 博客园都有这个问题

**Comment by 775728212** [comment]
什么时候修复一下

**Comment by onblog** [comment]
尽快

**Comment by onblog** [comment]
1.0.30版本已经修复上传文章bug
